### ISSUE TITLE
Practica 3: Despliegue en Heroku

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-edith#2]
[Práctica 3 Despliegue en Heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-edith/files/8352631/Practica.3.Despliegue.en.Heroku.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo, cumple con todos los puntos a evaluar 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
